(()=>{
  if(typeof state==='undefined') return;
  const ds=window.PersonalOSData;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v)||0);
  const dateTime=v=>{if(!v)return'—';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})};
  const dateOnly=v=>{if(!v)return'—';const d=new Date(String(v).slice(0,10)+'T12:00:00');return isNaN(d)?String(v):d.toLocaleDateString('en-US',{month:'short',day:'numeric'})};
  const source=t=>String(t?.sourceSystem||t?.source_system||'personal_os').toLowerCase();
  const isDone=t=>!!state.completed?.[t?.id]||['done','completed','cancelled'].includes(String(t?.status||'').toLowerCase());

  function ensureHead(){
    if(!document.querySelector('link[rel="manifest"]')){
      const l=document.createElement('link');l.rel='manifest';l.href='./manifest.webmanifest';document.head.appendChild(l);
    }
    if(!document.querySelector('link[rel="icon"]')){
      const l=document.createElement('link');l.rel='icon';l.href='./icon.svg';l.type='image/svg+xml';document.head.appendChild(l);
    }
    const metas=[['apple-mobile-web-app-capable','yes'],['apple-mobile-web-app-status-bar-style','default'],['apple-mobile-web-app-title','Personal OS']];
    metas.forEach(([name,content])=>{if(!document.querySelector(`meta[name="${name}"]`)){const m=document.createElement('meta');m.name=name;m.content=content;document.head.appendChild(m)}});
  }
  ensureHead();
  if('serviceWorker' in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(e=>console.warn('sw',e)));

  let installPrompt=null;
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;document.body.dataset.pwaInstall='ready';});
  const standalone=()=>window.matchMedia?.('(display-mode: standalone)').matches||window.navigator.standalone===true;

  function ensureStyles(){
    if(document.getElementById('prodPatchStyles'))return;
    const s=document.createElement('style');s.id='prodPatchStyles';s.textContent=`
      .prod-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:10px}.prod-card{background:#fff;border:1px solid var(--line);border-radius:12px;padding:13px}.prod-card span{font-size:8px;color:#8a94a6;display:block}.prod-card strong{font-size:18px;display:block;margin-top:4px}.prod-attention{display:grid;gap:7px}.prod-alert{border:1px solid #e6eaf0;border-radius:10px;padding:9px 10px;background:#fafbfe}.prod-alert.warn{background:#fff8ed;border-color:#f1dfbb}.prod-alert.good{background:#edf9f3;border-color:#d3efdf}.prod-alert b{font-size:10px;display:block}.prod-alert small{font-size:8px;color:#7b8799;display:block;margin-top:3px;line-height:1.4}
      .prod-overlay{position:fixed;inset:0;background:rgba(20,28,44,.38);backdrop-filter:blur(4px);z-index:10020;display:flex;align-items:center;justify-content:center;padding:18px}.prod-modal{width:min(720px,96vw);max-height:88vh;overflow:auto;background:#f7f9fc;border-radius:18px;box-shadow:0 30px 80px rgba(20,28,44,.25);padding:18px}.prod-modal-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:12px}.prod-modal h2{margin:2px 0;font-size:19px}.prod-modal-close{border:0;background:#e9edf4;border-radius:9px;width:32px;height:32px;cursor:pointer;font-size:18px}.prod-approval{background:#fff;border:1px solid var(--line);border-radius:12px;padding:12px;margin:8px 0}.prod-approval h4{font-size:11px;margin:0 0 5px}.prod-approval p{font-size:9px;color:#657086;line-height:1.5;margin:6px 0}.prod-row{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.prod-code{font:8px ui-monospace,SFMono-Regular,Menlo,monospace;background:#f1f3f7;padding:4px 6px;border-radius:6px;color:#5c6678}.prod-action{border:1px solid #dfe4ec;background:#fff;color:#4d5a70;border-radius:7px;padding:5px 8px;font-size:8px;font-weight:700;cursor:pointer}.prod-action.primary{background:#5a6eea;color:#fff;border-color:#5a6eea}.prod-highlight{outline:3px solid rgba(90,110,234,.2)!important;background:#f5f7ff!important;transition:.2s}
      .brief-inline-actions{display:flex;gap:5px;margin-top:7px;flex-wrap:wrap}.brief-inline-actions button{border:1px solid #dfe4ec;background:#fff;border-radius:7px;padding:5px 7px;font-size:8px;color:#4f5b70;cursor:pointer;font-weight:700}.brief-inline-actions button.primary{background:#5a6eea;color:#fff;border-color:#5a6eea}
      .prod-setting-card{background:#fff;border:1px solid var(--line);border-radius:13px;padding:15px;margin-top:12px}.prod-setting-card h3{font-size:11px;margin:0 0 3px}.prod-setting-card .sub{font-size:9px;color:#8993a4}.prod-toggle{display:flex;align-items:center;justify-content:space-between;padding:9px 0;border-bottom:1px solid #eef1f5;font-size:10px}.prod-toggle:last-child{border-bottom:0}.prod-toggle input{accent-color:#5a6eea}
      @media(max-width:1050px){.prod-grid{grid-template-columns:repeat(3,1fr)}}
      @media(max-width:720px){
        .nav{overflow-x:auto;justify-content:flex-start;scrollbar-width:none}.nav::-webkit-scrollbar{display:none}.nav button:nth-child(n){display:flex!important;min-width:48px;flex:1}.sidebar{height:64px}.main{padding-bottom:66px}.topbar{height:64px;padding:0 12px}.topbar h1{font-size:18px}.eyebrow{font-size:8px}.topbar-actions{gap:5px;align-items:center}#syncStatus,#authBtn,#globalSearch{display:none!important}#aiBriefBtn{display:inline-flex!important;font-size:0;padding:8px 9px}#aiBriefBtn:after{content:'✦';font-size:14px}#startDayBtn{display:inline-flex!important;padding:8px 10px;font-size:9px}.content{padding:12px 10px 82px}.card{border-radius:12px}.prod-grid{grid-template-columns:1fr 1fr}.prod-modal{width:100%;max-height:92vh;padding:14px}.brief-panel{width:100vw!important;padding:16px!important}.brief-panel-head{top:-16px!important}.finance-grid,.health-grid{grid-template-columns:1fr 1fr}.mini-table{font-size:8px}.mini-table th,.mini-table td{padding:7px 4px}.panel-head{align-items:flex-start;gap:8px}.panel-head .primary{font-size:9px;padding:8px 10px}
      }
    `;document.head.appendChild(s);
  }
  ensureStyles();

  function modal(inner){
    document.getElementById('prodOverlay')?.remove();
    const root=document.createElement('div');root.id='prodOverlay';root.className='prod-overlay';root.innerHTML=`<section class="prod-modal">${inner}</section>`;document.body.appendChild(root);
    const close=()=>root.remove();root.onclick=e=>{if(e.target===root)close()};root.querySelectorAll('[data-prod-close]').forEach(b=>b.onclick=close);return {root,close};
  }

  function primevaQueue(){
    const items=(state.primevaApprovals||[]).filter(a=>String(a.state||'pending').toLowerCase()==='pending').sort((a,b)=>String(b.requested_at||'').localeCompare(String(a.requested_at||'')));
    const body=items.length?items.map(a=>`<article class="prod-approval"><div class="prod-row"><span class="tag">${esc(a.brand||'shared')}</span><span class="tag">${esc(a.approval_type||'approval')}</span><span class="prod-code">${esc(a.external_id||'')}</span></div><h4>${esc(a.title)}</h4><p>${esc(a.summary||'No summary provided.')}</p><div class="prod-row"><span style="font-size:8px;color:#8a94a6">Requested ${dateTime(a.requested_at)}${a.related_record_id?` · related ${esc(a.related_record_id)}`:''}</span><button class="prod-action" data-copy-id="${esc(a.external_id||'')}">Copy approval ID</button>${a.related_record_id?`<button class="prod-action" data-copy-id="${esc(a.related_record_id)}">Copy related ID</button>`:''}</div></article>`).join(''):'<div class="hint">No pending Primeva approvals.</div>';
    const {root}=modal(`<div class="prod-modal-head"><div><div class="eyebrow">PRIMEVA · READ-ONLY</div><h2>Decision queue</h2><div class="hint">Personal OS surfaces context only. Approvals, sends, publishing and spending still happen in Primeva.</div></div><button class="prod-modal-close" data-prod-close>×</button></div>${body}<div class="prod-row" style="margin-top:12px"><button class="secondary" data-prod-close>Close</button></div>`);
    root.querySelectorAll('[data-copy-id]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(b.dataset.copyId);toast('Primeva ID copied')}catch{toast(b.dataset.copyId)}});
  }

  function connectedTaskDetails(task){
    modal(`<div class="prod-modal-head"><div><div class="eyebrow">${esc(task.area||'CONNECTED SOURCE')}</div><h2>${esc(task.title)}</h2><div class="hint">${esc(source(task).replace('_',' '))} · read-only in Personal OS</div></div><button class="prod-modal-close" data-prod-close>×</button></div><article class="prod-approval"><div class="prod-row"><span class="tag">${esc(task.status||'Open')}</span>${task.priority?`<span class="tag">${esc(task.priority)}</span>`:''}</div><p>${esc(task.notes||'No additional source notes.')}</p><div class="hint">Due: ${task.dueAt?dateTime(task.dueAt):dateOnly(task.due)}. Complete or change this item in its source system; the next sync will update Personal OS.</div></article><button class="secondary" data-prod-close>Close</button>`);
  }

  function highlightText(title){
    const wanted=String(title||'').trim().toLowerCase();if(!wanted)return;
    setTimeout(()=>{const els=[...document.querySelectorAll('#content b,#content .task-title,#content .sched-task-title')];const hit=els.find(e=>e.textContent.trim().toLowerCase()===wanted)||els.find(e=>e.textContent.trim().toLowerCase().includes(wanted));if(hit){const box=hit.closest('tr,.check-row,.sched-task,.area-column,.card')||hit;box.classList.add('prod-highlight');box.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>box.classList.remove('prod-highlight'),2600)}},80);
  }
  function openTask(task){if(!task)return;state.route='tasks';render();highlightText(task.title)}
  async function completeTask(task){
    if(!task||task.readOnly){connectedTaskDetails(task);return;}
    try{if(ds?.user)await ds.setCompleted(task.id,true);state.completed[task.id]=true;toast('Task completed');if(typeof refreshFromSupabase==='function'&&ds?.user)await refreshFromSupabase();else render();}catch(e){toast(e.message||'Unable to complete task')}
  }
  function openCalendar(title){state.route='calendar';render();highlightText(title)}

  function enhanceBrief(){
    const ov=document.getElementById('liveBriefOverlay');if(!ov||ov.dataset.prodEnhanced)return;ov.dataset.prodEnhanced='1';
    const sections=[...ov.querySelectorAll('.brief-section')];
    const top=sections.find(s=>s.querySelector('h4')?.textContent.trim()==='TOP 3');
    top?.querySelectorAll('.brief-line').forEach(line=>{
      const title=line.querySelector('b')?.textContent.trim()||'';const actions=document.createElement('div');actions.className='brief-inline-actions';
      if(/^Review \d+ Primeva approval/i.test(title)){actions.innerHTML='<button class="primary">Review decision queue</button>';actions.firstElementChild.onclick=primevaQueue;}
      else if(title.startsWith('Prepare for ')){const eventTitle=title.replace(/^Prepare for /,'');actions.innerHTML='<button>Open Calendar</button>';actions.firstElementChild.onclick=()=>openCalendar(eventTitle);}
      else {const task=(state.tasks||[]).find(t=>String(t.title||'').trim()===title);if(task){actions.innerHTML=task.readOnly?'<button>View source context</button><button>Open Tasks</button>':'<button class="primary">Complete</button><button>Open Tasks</button>';const bs=actions.querySelectorAll('button');if(task.readOnly){bs[0].onclick=()=>connectedTaskDetails(task);bs[1].onclick=()=>openTask(task)}else{bs[0].onclick=()=>completeTask(task);bs[1].onclick=()=>openTask(task)}}}
      if(actions.children.length)line.querySelector('div:last-child')?.appendChild(actions);
    });
    sections.forEach(sec=>{const h=sec.querySelector('h4')?.textContent.trim();if(h==='RESPONSES & APPROVALS'&&(state.primevaApprovals||[]).some(a=>String(a.state).toLowerCase()==='pending')){const d=document.createElement('div');d.className='brief-inline-actions';d.innerHTML='<button class="primary">Review all Primeva approvals</button>';d.firstElementChild.onclick=primevaQueue;sec.appendChild(d)}if(h==='FINANCE EXCEPTION'){const d=document.createElement('div');d.className='brief-inline-actions';d.innerHTML='<button>Open Finance</button>';d.firstElementChild.onclick=()=>{document.getElementById('liveBriefOverlay')?.remove();state.route='finance';render()};sec.appendChild(d)}if(h==='WHOOP READINESS'){const d=document.createElement('div');d.className='brief-inline-actions';d.innerHTML='<button>Open Health</button>';d.firstElementChild.onclick=()=>{document.getElementById('liveBriefOverlay')?.remove();state.route='health';render()};sec.appendChild(d)}});
  }
  new MutationObserver(enhanceBrief).observe(document.body,{childList:true,subtree:true});

  function monthlyAmount(r){const amt=Math.abs(Number(r.last_amount??r.average_amount??0));const f=String(r.frequency||'monthly').toLowerCase();if(f.includes('week')&&!f.includes('bi'))return amt*52/12;if(f.includes('bi')&&f.includes('week'))return amt*26/12;if(f.includes('semi'))return amt*2;if(f.includes('quarter'))return amt/3;if(f.includes('year')||f.includes('annual'))return amt/12;if(f.includes('day'))return amt*365/12;return amt;}
  function financeModel(){
    const fs=financeStats();const credits=(state.financeAccounts||[]).filter(a=>a.account_type==='credit');const creditBalance=credits.reduce((s,a)=>s+Math.max(0,Number(a.current_balance||0)),0);const knownLimits=credits.reduce((s,a)=>s+Math.max(0,Number(a.credit_limit||0)),0);const util=knownLimits?creditBalance/knownLimits*100:null;const monthly=(state.recurringFinance||[]).reduce((s,r)=>s+monthlyAmount(r),0);
    const start=new Date();start.setHours(0,0,0,0);const end7=new Date(start.getTime()+7*86400000);const upcoming=(state.recurringFinance||[]).map(r=>({r,d:r.predicted_next_date?new Date(String(r.predicted_next_date).slice(0,10)+'T12:00:00'):null,amt:Math.abs(Number(r.last_amount??r.average_amount??0))})).filter(x=>x.d&&!isNaN(x.d)&&x.d>=start&&x.d<=end7).sort((a,b)=>a.d-b.d);const liabs=(state.liabilities||[]).map(l=>({l,d:(l.next_payment_due||l.next_payment_due_date)?new Date(String(l.next_payment_due||l.next_payment_due_date).slice(0,10)+'T12:00:00'):null,amt:Math.abs(Number(l.minimum_payment??l.minimum_payment_amount??l.next_monthly_payment??0))})).filter(x=>x.d&&!isNaN(x.d)&&x.d>=start&&x.d<=end7).sort((a,b)=>a.d-b.d);const due7=upcoming.reduce((s,x)=>s+x.amt,0)+liabs.reduce((s,x)=>s+x.amt,0);const pastDue=(state.liabilities||[]).reduce((s,l)=>s+Math.max(0,Number(l.past_due_amount||0)),0);const history=(state.financeHistory||[]).slice().sort((a,b)=>String(a.snapshot_date).localeCompare(String(b.snapshot_date)));return {fs,credits,creditBalance,knownLimits,util,monthly,upcoming,liabs,due7,pastDue,history};
  }
  function financeAlerts(m){const a=[];if(m.pastDue>0)a.push({tone:'warn',title:`Past-due amount detected · ${money(m.pastDue)}`,detail:'Open the underlying liability account and verify whether this has already been paid or is still outstanding.'});if(m.util!=null&&m.util>=30)a.push({tone:'warn',title:`Known-limit card utilization · ${m.util.toFixed(0)}%`,detail:`${money(m.creditBalance)} across ${money(m.knownLimits)} of reported credit limits. Cards without a reported limit are excluded.`});if(m.due7>0)a.push({tone:'',title:`Next 7 days · ${money(m.due7)} tracked obligations`,detail:`Includes ${m.upcoming.length} recurring item${m.upcoming.length===1?'':'s'} and ${m.liabs.length} liability payment${m.liabs.length===1?'':'s'} with known dates.`});if(m.history.length<7)a.push({tone:'',title:`Net-position history · ${m.history.length} daily snapshot${m.history.length===1?'':'s'}`,detail:'The trend becomes more informative as the daily Finance Sync adds history.'});if(!a.length)a.push({tone:'good',title:'No urgent finance exception detected',detail:'Review the account and recurring-obligation tables for routine maintenance.'});return a.slice(0,4)}

  const priorFinance=financePage;
  financePage=function(){
    const m=financeModel(),fs=m.fs;const finSync=integration('finance')||integration('finances');const rec=(state.recurringFinance||[]).slice().sort((a,b)=>String(a.predicted_next_date||'9999').localeCompare(String(b.predicted_next_date||'9999'))).slice(0,14);const histVals=m.history.map(x=>Number(x.estimated_net_position||0));const cashVals=m.history.map(x=>Number(x.liquid_cash||0));const alerts=financeAlerts(m);
    const manualDebt=(state.assets||[]).filter(a=>['auto_loan','student_loan','mortgage','credit_card','other_debt'].includes(String(a.asset_category||''))||String(a.asset_category||'').includes('debt'));
    return `<div class="section-stack"><div class="panel-head"><div><h2>Finance Command Center</h2><div style="font-size:10px;color:#8c96a8">Balances, obligations and trend signals from connected Finance data. Last sync ${finSync?.last_synced_at?dateTime(finSync.last_synced_at):'pending'}.</div></div><span class="tag">${esc(finSync?.status||'connected')}</span></div>
      <div class="prod-grid"><div class="prod-card"><span>EST. NET POSITION</span><strong>${money(fs.net)}</strong></div><div class="prod-card"><span>LIQUID CASH</span><strong>${money(fs.cash)}</strong></div><div class="prod-card"><span>INVESTMENTS</span><strong>${money(fs.inv)}</strong></div><div class="prod-card"><span>TRACKED DEBT</span><strong>${money(fs.debt)}</strong></div><div class="prod-card"><span>MONTHLY RECURRING</span><strong>${money(m.monthly)}</strong></div><div class="prod-card"><span>KNOWN-LIMIT UTIL.</span><strong>${m.util==null?'—':m.util.toFixed(0)+'%'}</strong></div></div>
      <div class="grid grid-2"><article class="card chart-card"><div class="chart-title"><div><h3>NET POSITION / LIQUIDITY TREND</h3><div class="chart-sub">Daily snapshots · ${m.history.length} day${m.history.length===1?'':'s'}</div></div><span class="tag">Daily</span></div>${m.history.length>1?lineChartSvg([{values:histVals,color:'#5a6eea'},{values:cashVals,color:'#21b69a'}]):barSvg([Math.max(fs.cash,1),Math.max(fs.inv,1),Math.max(fs.asset,1),Math.max(fs.debt,1)],'#5a6eea')}<div class="legend"><span><i class="dot" style="background:#5a6eea"></i>Net position</span><span><i class="dot" style="background:#21b69a"></i>Liquid cash</span></div></article><article class="card card-pad"><div class="card-title"><h3>FINANCE ATTENTION</h3><span class="tag">Exception based</span></div><div class="prod-attention">${alerts.map(x=>`<div class="prod-alert ${x.tone}"><b>${esc(x.title)}</b><small>${esc(x.detail)}</small></div>`).join('')}</div></article></div>
      <div class="grid grid-2"><article class="card card-pad"><div class="card-title"><h3>UPCOMING OBLIGATIONS</h3><span class="tag">Next 14 visible</span></div><table class="mini-table"><thead><tr><th>NEXT</th><th>ITEM</th><th>CADENCE</th><th>AMOUNT</th></tr></thead><tbody>${rec.map(r=>`<tr><td>${dateOnly(r.predicted_next_date)}</td><td>${esc(r.description||r.merchant_name||'Recurring item')}</td><td>${esc(r.frequency||r.recurring_type||'—')}</td><td>${money(r.last_amount??r.average_amount)}</td></tr>`).join('')||'<tr><td colspan="4">No recurring obligations available.</td></tr>'}</tbody></table></article><article class="card card-pad"><div class="card-title"><h3>ACCOUNTS</h3><span class="tag">${state.financeAccounts.length}</span></div><table class="mini-table"><thead><tr><th>INSTITUTION</th><th>ACCOUNT</th><th>TYPE</th><th>BALANCE</th></tr></thead><tbody>${state.financeAccounts.map(a=>`<tr><td>${esc(a.institution||'—')}</td><td>${esc(a.account_name||'—')}${a.mask?' · '+esc(a.mask):''}</td><td>${esc(a.account_subtype||a.account_type||'—')}</td><td>${money(a.current_balance)}</td></tr>`).join('')||'<tr><td colspan="4">No accounts available.</td></tr>'}</tbody></table></article></div>
      <div class="grid grid-2"><article class="card card-pad"><div class="card-title"><h3>ASSETS & INVESTMENTS</h3></div>${state.holdings.map(h=>`<div class="list-row"><span>${esc(h.name||h.ticker_symbol||h.account_name||'Holding')}</span><strong>${money(h.institution_value)}</strong></div>`).join('')}${state.assets.filter(a=>!manualDebt.includes(a)).map(a=>`<div class="list-row"><span>${esc(a.name)}</span><strong>${money(a.current_worth)}</strong></div>`).join('')||'<div class="hint">No additional assets tracked.</div>'}</article><article class="card card-pad"><div class="card-title"><h3>DEBT / LIABILITY TERMS</h3></div>${state.liabilities.map(l=>`<div class="list-row"><span>${esc(l.account_name||l.liability_type||'Liability')}<br><small>${l.interest_rate!=null?`${Number(l.interest_rate).toFixed(2)}% · `:''}${l.next_payment_due?`due ${dateOnly(l.next_payment_due)}`:''}</small></span><strong>${money(l.current_balance||l.last_statement_balance||0)}</strong></div>`).join('')}${manualDebt.map(a=>`<div class="list-row"><span>${esc(a.name)}<br><small>${esc(a.asset_category||'tracked debt')}</small></span><strong>${money(a.current_worth)}</strong></div>`).join('')||'<div class="hint">No detailed liabilities available.</div>'}</article></div>
    </div>`;
  };

  const PREF='pos_notification_prefs_v1';
  function prefs(){try{return Object.assign({calendar:true,threeRivers:true,primeva:true,supplements:true},JSON.parse(localStorage.getItem(PREF)||'{}'))}catch{return {calendar:true,threeRivers:true,primeva:true,supplements:true}}}
  function savePrefs(p){localStorage.setItem(PREF,JSON.stringify(p))}
  const LOG='pos_notification_log_v1';
  function notifyLog(){try{return JSON.parse(localStorage.getItem(LOG)||'{}')}catch{return{}}}
  function markNotified(tag){const l=notifyLog();l[tag]=Date.now();const cutoff=Date.now()-8*86400000;Object.keys(l).forEach(k=>{if(l[k]<cutoff)delete l[k]});localStorage.setItem(LOG,JSON.stringify(l))}
  async function sendNotification(title,body,tag){if(!('Notification'in window)||Notification.permission!=='granted')return;const l=notifyLog();if(l[tag])return;markNotified(tag);try{if('serviceWorker'in navigator){const r=await navigator.serviceWorker.ready;await r.showNotification(title,{body,tag,icon:'./icon.svg',badge:'./icon.svg'})}else new Notification(title,{body,tag})}catch(e){console.warn('notification',e)}}
  function checkNotifications(){
    if(!state.live||Notification.permission!=='granted')return;const p=prefs(),n=new Date();
    if(p.calendar){(state.events||[]).forEach(e=>{const d=new Date(e.starts_at);const mins=(d-n)/60000;if(mins>=0&&mins<=30)sendNotification(e.area||'Calendar',`${e.title} · ${dateTime(e.starts_at)}`,`event:${e.external_id||e.id||e.title}:${String(e.starts_at).slice(0,16)}`)})}
    if(p.threeRivers){(state.tasks||[]).filter(t=>source(t)==='three_rivers'&&!isDone(t)).forEach(t=>{const d=t.dueAt?new Date(t.dueAt):null;if(d){const hrs=(d-n)/3600000;if(hrs>=0&&hrs<=2)sendNotification('Three Rivers due soon',`${t.title} · ${dateTime(t.dueAt)}`,`tr:${t.id}:${String(t.dueAt).slice(0,13)}`)}})}
    if(p.primeva){const old=(state.primevaApprovals||[]).filter(a=>String(a.state).toLowerCase()==='pending'&&a.requested_at&&(n-new Date(a.requested_at))>=24*3600000);if(old.length)sendNotification('Primeva approvals waiting',`${old.length} approval${old.length===1?' has':'s have'} been pending more than 24 hours.`, `primeva:${n.toISOString().slice(0,10)}:${old.length}`)}
    if(p.supplements){const hm=n.toTimeString().slice(0,5),day=n.toLocaleDateString('en-CA');(state.supplements||[]).filter(s=>s.active&&s.reminder_enabled&&String(s.reminder_time||'').slice(0,5)===hm).forEach(s=>sendNotification('Personal OS reminder',s.name,`supp:${s.id}:${day}:${hm}`))}
  }
  setInterval(checkNotifications,60000);setTimeout(checkNotifications,2500);

  function appSettingsPanel(){const p=prefs();const permission=('Notification'in window)?Notification.permission:'unsupported';const installed=standalone();return `<div class="prod-setting-card"><div class="card-title"><div><h3>PERSONAL OS APP</h3><div class="sub">Installable PWA + local alert controls.</div></div><span class="tag">${installed?'installed':'web app'}</span></div><div class="prod-row"><button class="primary" id="prodInstall">${installed?'Installed':'Install Personal OS'}</button><button class="secondary" id="prodNotifications">${permission==='granted'?'Notifications enabled':'Enable notifications'}</button></div><p class="hint" style="margin-top:10px">On iPhone/iPad, Safari may use Share → Add to Home Screen instead of showing an install prompt.</p><div style="margin-top:10px"><label class="prod-toggle"><span>Calendar events within 30 minutes</span><input type="checkbox" data-prod-pref="calendar" ${p.calendar?'checked':''}></label><label class="prod-toggle"><span>Three Rivers items within 2 hours</span><input type="checkbox" data-prod-pref="threeRivers" ${p.threeRivers?'checked':''}></label><label class="prod-toggle"><span>Primeva approvals waiting 24+ hours</span><input type="checkbox" data-prod-pref="primeva" ${p.primeva?'checked':''}></label><label class="prod-toggle"><span>Configured supplement reminder times</span><input type="checkbox" data-prod-pref="supplements" ${p.supplements?'checked':''}></label></div></div>`}
  function securityPanel(){return `<div class="prod-setting-card"><div class="card-title"><div><h3>PRIMEVA SECURITY</h3><div class="sub">Owner-only database access model.</div></div><span class="tag"><span class="status-dot" style="background:#2daf72"></span>hardened</span></div><div class="list-row"><span>Operational tables</span><strong>17 · RLS enabled</strong></div><div class="list-row"><span>Public pv_* views</span><strong>Security invoker</strong></div><div class="list-row"><span>Anonymous Primeva access</span><strong>Revoked</strong></div><div class="list-row"><span>Pending decisions</span><button class="small-link" id="prodPrimevaQueue">${(state.primevaApprovals||[]).filter(a=>String(a.state).toLowerCase()==='pending').length} · Review →</button></div><p class="hint" style="margin-top:10px">Backend/service ingest remains available; Personal OS remains read-only for Primeva execution.</p></div>`}
  function healthSourcesPanel(){const w=integration('whoop'),a=integration('apple_health');return `<div class="prod-setting-card"><div class="card-title"><div><h3>HEALTH SOURCES</h3><div class="sub">Only connected sources are treated as live.</div></div></div><div class="list-row"><span>WHOOP</span><strong>${esc(w?.status||'connected')}</strong></div><div class="list-row"><span>WHOOP workouts</span><strong>${state.workoutLogs.filter(x=>x.source_system==='whoop').length}</strong></div><div class="list-row"><span>Apple Health</span><strong>${esc(a?.status||'not connected')}</strong></div><p class="hint" style="margin-top:10px">Apple Health is not connected through the current Health integration, so Personal OS does not invent steps, Apple workouts, or clinical data. WHOOP remains the active wearable source.</p></div>`}
  const priorSettings=settingsPage;
  settingsPage=function(){return priorSettings()+`<div class="grid grid-2" style="margin-top:14px"><div>${appSettingsPanel()}${healthSourcesPanel()}</div><div>${securityPanel()}</div></div>`};

  const prevBind=bind;
  bind=function(){
    prevBind();
    document.getElementById('prodPrimevaQueue')?.addEventListener('click',primevaQueue);
    const ins=document.getElementById('prodInstall');if(ins)ins.onclick=async()=>{if(standalone()){toast('Personal OS is already installed.');return}if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;toast('Install prompt completed.')}else{toast('On Safari: Share → Add to Home Screen. On Chrome: use Install in the address bar/menu.')}};
    const nb=document.getElementById('prodNotifications');if(nb)nb.onclick=async()=>{if(!('Notification'in window)){toast('Browser notifications are not supported here.');return}const result=await Notification.requestPermission();toast(result==='granted'?'Notifications enabled':'Notifications were not enabled');render()};
    document.querySelectorAll('[data-prod-pref]').forEach(c=>c.onchange=()=>{const p=prefs();p[c.dataset.prodPref]=c.checked;savePrefs(p);toast('Notification preference saved')});
    if(state.route==='overview')setTimeout(enhanceBrief,0);
  };

  if(typeof render==='function')render();
})();
